# Generated by Django 5.1.2 on 2024-10-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='priority',
        ),
    ]
