# Generated by Django 5.1.2 on 2024-10-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlistitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistcategory',
            name='description',
        ),
    ]
