# Generated by Django 5.1.1 on 2024-10-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_diskusi', '0004_post_resto_restaurant_alcohol_served_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forum_diskusi.restaurant'),
        ),
    ]
