# Generated by Django 5.1 on 2024-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
