# Generated by Django 5.1 on 2024-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto_rating', '0002_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
    ]
