# Generated by Django 5.1.1 on 2024-10-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
