# Generated by Django 5.1.1 on 2024-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='Steak house with a variety of dishes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default='07:00:00'),
        ),
    ]
