# Generated by Django 5.1.1 on 2024-10-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='Steak house with a variety of dishes \n and a great view of the city'),
        ),
    ]
