# Generated by Django 5.1.1 on 2024-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='special_menu',
            field=models.CharField(default='Steak', max_length=100),
        ),
    ]
