# Generated by Django 5.1.1 on 2024-10-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0009_restaurant_special_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='special_menu',
            field=models.CharField(max_length=100),
        ),
    ]
